### ISSUE TITLE
Dr. Pascal 

### ISSUE THREAD

**Issue by ChirazeHaidar** [ChirazeHaidar/vc#1]
Bonjour, j'ai déjà fait le fork.
J'ai mis les collaborateurs.
Le backlog est fin, Je veux seulement savoir où on doit le mettre

**Comment by pascalfares** [comment]
Ici dans ce git ... 

me transmettre le fichier au fermat text, je vous montrerais comment faire...

**Comment by ChirazeHaidar** [comment]
J'ai déjà mis le backlog
Si c'est bien, on commence le travail

**Comment by ChirazeHaidar** [comment]
bonsoir Dr. Pascal
j'ai fait mon compte Google Cloud
j'ai commencé à travailler sur firebase depuis le console du cloud.
Vous avez dit que c'est noté, comment on va vous montrer qu'on a fini ce travail
merci cordialement

**Comment by pascalfares** [comment]
Je verrais car vous le documenterez vous même quelques part de visible

par exemple dans des docs au format MarkDown comme j'ai fait ici https://github.com/projets2017cl/vc/tree/master/GestionSuiviBien

ou là https://github.com/projets2017cl/vc/tree/master/SousProjets
