### ISSUE TITLE
Coordinateur du Team Phoenix

### ISSUE THREAD

**Issue by ChirazeHaidar** [ChirazeHaidar/vc#11]
Backlog
Etude la base de données
Division du Travail selon les capacités de chaque collaborateur

**Comment by pascalfares** [comment]
Ne diviser pas le travail...

faire un besoin, une demande ou une tache dans "issue"...

celui qui souhaite le faire fera l'activité...

ESSAYER

**Comment by ChirazeHaidar** [comment]
D'accord, les issues déjà faites sont d'après un meeting qu'on a fait ensemble, on c'est mis d'accord à suivre ce démarche avec la possibilité de s'aider.

**Comment by pascalfares** [comment]
Une issue dans projets2017cl/vc ===> un travail à réalisé dans le fork (un commit ou plusieurs commit) => pullrequest => si pullrequest accépté CLOSE issue

**Comment by pascalfares** [comment]
Moi le gestionaire global du projet je vais vous suivre en regardant les issue uniquement dans projets2017cl/vc et les pullrequest.

Vos issue dans les fork sont pour vous même (je viendrais bien sure de temps en temps vous aider)
