### ISSUE TITLE
Application mobile: Quelle sont les fonctionnalités à réaliser?

### ISSUE THREAD

**Issue by ayounes3333** [ChirazeHaidar/vc#12]

**Comment by ayounes3333** [comment]
que pensez vous?

**Comment by pascalfares** [comment]
Que penser de quoi?

**Comment by ayounes3333** [comment]
Des idées pour commencer

**Comment by elieohanian** [comment]
hi Ali,
on doit commencer par suivre le schema, voit le base de donne(schema)

- creer supplier
- creer client
- creer brand
- relier supplier avec brand
- creer product (check schema)
- transaction pour faire l'entrer au stock

**Comment by ayounes3333** [comment]
Okk mercii

**Comment by elieohanian** [comment]
Hi Ali,

j'ai commence par creer les class

**Comment by pascalfares** [comment]
Inventaire de stock (offline) avec synchronisation pour consolidation et report d'ecart entre la BD et le réel

**Comment by ayounes3333** [comment]
okk bien
