### ISSUE TITLE
Firebase & Milestone

### ISSUE THREAD

**Issue by ChirazeHaidar** [ChirazeHaidar/vc#13]
pour commencer la base de données, je dois créer un projet depuis firebase?
c'est quoi le milestone dans github?
merci

**Comment by pascalfares** [comment]
Non pas nécessairement ... pourquoi Firebase? Fitrebase est une des possibilité, mais Mysql est plus adapté au début.

Un milestone c'est pour donner une date de livraison attendu pour un "Sprint" Je vais vous en créer un!

**Comment by pascalfares** [comment]
sI VOUS TROUVEZ QUE LA RÉPONSE EST SATISFAISANTE OU QUE LE TRAVAIL demandé est rtéalisé vous pouvez fermé l'issue

**Comment by ChirazeHaidar** [comment]
merci beaucoup
j'ai bien compris
