### ISSUE TITLE
Github Fichier Pack large

### ISSUE THREAD

**Issue by ayounes3333** [ChirazeHaidar/vc#14]
Bonjour Dr. 
Hier j'ai comité par accident des fichiers larges, après nettoyage du projet, les fichiers d'histoire (Pack Files: .git/objects/pack) seront très larges (>20 Mo). Qu'est-ce qu'il faut faire?

**Comment by ayounes3333** [comment]
J'ai trouvé plusieurs solutions mais on peut perdre le log des commit par conséquence

**Comment by pascalfares** [comment]
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by ayounes3333** [comment]
Okk mercii baucoup
