### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by elieohanian** [ChirazeHaidar/vc#16]
https://www.dropbox.com/sh/xq263ny3jzv5hl5/AADmUB6EBYHA0H0NBFmIF2JRa?dl=0

MYSQL Databse with APache server

**Comment by pascalfares** [comment]
Je vous conseil sérieusement d'avoir une BOX linux

Linux + Apache + Mysql + Tomcat (ou tomee) comme configuration de déploient

Configuration identique dans "deploy" et developpement

pour faire ceci soit 

1- Installer Linux (Bareemetal) et vous habituer a travailler sous Linux, et développer toujours comme ceci (vous garantirez votre avenir) poser vous la question pourquoi ceci http://www.zdnet.fr/actualites/windows-10-ubuntu-fait-son-entree-dans-le-windows-store-39854934.htm ?

2- soit dans une machine virtuelle (juste la partie serveur) Ubuntu server par exemple
3- soit avec docker

**Comment by elieohanian** [comment]
@ChirazeHaidar  Please check docteur pascal commentaire

**Comment by elieohanian** [comment]
@ChirazeHaidar  I can perepare  ubuntu virtual machine, check with the team

**Comment by ChirazeHaidar** [comment]
I already have ubuntu on a virtual machine, it's already prepared. let talk in our next meeting
