### ISSUE TITLE
Android Screens

### ISSUE THREAD

**Issue by elieohanian** [ChirazeHaidar/vc#17]
Your Opinion please
[Android Screens(Elie Ohanian).docx](https://github.com/ChirazeHaidar/vc/files/1158718/Android.Screens.Elie.Ohanian.docx)

**Comment by ayounes3333** [comment]
![splash screen](https://user-images.githubusercontent.com/12007486/28406874-c7a4c204-6d3a-11e7-9e53-b917643f4c7d.png)
![ajouter_client](https://user-images.githubusercontent.com/12007486/28406873-c7a355c2-6d3a-11e7-9a91-d7dc9579e230.png)
![login](https://user-images.githubusercontent.com/12007486/28406872-c7a300c2-6d3a-11e7-9603-7e833378eeec.png)

**Comment by pascalfares** [comment]
C'est pas très bien de mettre des raw file dans le git ( a cause du volume) 

Les images, les vid´eo etc.. devrait être dans une service externe avec lien ici
