### ISSUE TITLE
Business Requirements 

### ISSUE THREAD

**Issue by elieohanian** [ChirazeHaidar/vc#18]
[business requirement .docx](https://github.com/ChirazeHaidar/vc/files/1161432/business.requirement.docx)

**Comment by pascalfares** [comment]
@elieohanian 
Faire un fichier .md dans /docs

**Comment by elieohanian** [comment]
@pascalfares   on en entrain de metter nos notes (  le team) @ChirazeHaidar  veut prepare tous nos notes dans un seul ficher
