### ISSUE TITLE
BD et Java Entities

### ISSUE THREAD

**Issue by pascalfares** [ChirazeHaidar/vc#19]
Vous devriez terminer rapidement la partie modèle de données (au moins la version 0)

1. Créer vos tables (ou shemas)
2. Les classes Java représentant les entité
3. Les classe d'accès au donnée que vous developper vous même (4 methodes minimum Create, Read, Update, Delete) 

L'avantage de faire le 3 a la main! est de pourvoir definir la couche d'accès au dennée en fonction de votre besoin (par exemple soit directement BD ou a travaers des service web) aisi la parie essentielle sont les classes Java pas la BD !

Voici une exemple pour vous inspirer http://ljug.cofares.net/2013/09/simple-crud-using-jsf-primeface-and.html

**Comment by ChirazeHaidar** [comment]
On est entrain de le faire, les tables et schémas seront finis au début de la semaine prochaine

**Comment by pascalfares** [comment]
Vous pouvez aussi commencer par le modèle de classe et les classe en Pure Java avant... Ceci est stable ...

Ensuite en fonction du choix de la persitance de données (SQL, NoSQL, pure texte, etc...) vous ferez le nécessaire cotté serveur de données
