### ISSUE TITLE
C'est la liste finale des collaborateurs?

### ISSUE THREAD

**Issue by pascalfares** [ChirazeHaidar/vc#2]
1. Abdel Majid Nadar « 10215f »
2. Ali Chreif « 7880 »
3. Ali Younes « 9902 »
4. Chiraze Haydar « 2876f »
5. Elias Zgeib « 8114f »
6. Elie Ohanian « 9290f »
7. Firass Semaan « 3291f »
8. Khalil Bsaibes « 726z »
9. Mike Rmaily « 6504f »
10. Mohamed Faour « 3141f »

**Comment by ChirazeHaidar** [comment]
Oui, c'est la liste finale

**Comment by pascalfares** [comment]
Elie Semble vous avoir quitté?

**Comment by elieohanian** [comment]
No docteur
On travail par group
