### ISSUE TITLE
Google Drive Link For Doc Editing and Sharing

### ISSUE THREAD

**Issue by khalilbsaibesisae** [ChirazeHaidar/vc#20]
We will be using google drive folder to submit doc changes, so at the end we join all files into one file and upload to github.
https://drive.google.com/drive/folders/0B27GOXy5t85-OXhkTHpqOTk3b0U?usp=sharing

**Comment by pascalfares** [comment]
ne jamais uploader des raw file dans le git. le git est fait pour le codage. On peut y mettre des fichier explicatif text au fomat markdown comme le README.md) mais pas plus. Sinon les clone et les pull sont consomateur de bande passante sans interret car les différence ne sont pas trackable dans des fichirs binaire.


# VOUS POUVER

Faire une docs du projet en ligne (wiki, ou site, etc...) avec les liens qui vont bien.  En voici un exemple https://projets2017cl.github.io/vc/ (le resultat de ce lien provies du repertoire docs)
