### ISSUE TITLE
Build service layer using spring

### ISSUE THREAD

**Issue by chreifa** [ChirazeHaidar/vc#21]
a la fin de cette tache nous allons avoir une vision claire comment construire les services en utilisant spring framework.

**Comment by pascalfares** [comment]
N'utiliser pas Spring!  

Faire du pure standard j2ee 7 avec JSF.

Le JSF2 remplace et correspond a la version standard de tout les ancien framewok tel que Spring qui ne sont pas des standard.

**Comment by pascalfares** [comment]
En fait de quelle service il s'agit?

**Comment by elyzgheib** [comment]
Bonjour Dr. Pascal,

Est-ce que c'est acceptable d'utiliser JSP au lieu de JSF s'il fait le
nécessaire? Car la plupart entre nous n'a jamais utilisé JSF et on devra
consommé du temps pour l'apprendre et s'adapter à l'utiliser pour le
developement, tandis que avec JSP ça sera plus rapide à mon avis..."time is
money"

**Comment by chreifa** [comment]
c pour tous les services qui vont être utilisés par le mobile/ web... pour se communiquer avec la base de donnée.

**Comment by pascalfares** [comment]
Pour les serviceweb pas besoin ni de JSP ni de JSF juste la librairie standard JAX-RS, vous choisissez par exemple tomee comme serveur et plus rien d'autre a faire.

Si vous choisisser tomcat ajouter avotre projet la librairie JAX-RS de votre choix 

http://docs.oracle.com/javaee/6/tutorial/doc/giepu.html
http://jersey.java.net/
http://tomee.apache.org/

UN AUTRE CONSEIL:  UTILISER NETBEANS: plus simple dans le cadre de projets j2se, j2ee! surtout si vous êtes débutant
