### ISSUE TITLE
DB Credentials

### ISSUE THREAD

**Issue by khalilbsaibesisae** [ChirazeHaidar/vc#23]
We have created the db on google cloud platform
IP: 35.189.250.88
USER: phoenixisaeproject
PASS: (Sent Via Whatsapp) - PS: When committing your project to github, please exclude the db config file, so the password will not be exposed to the public, and therefore it will cause us a security breach.
DB NAME: gestiondesbiens

**Comment by pascalfares** [comment]
il faut faire un fichier .gitignore et ajouter ce qu'il faut

**Comment by ChirazeHaidar** [comment]
Deja fini
