### ISSUE TITLE
Sprint 1: Users

### ISSUE THREAD

**Issue by khalilbsaibesisae** [ChirazeHaidar/vc#24]
I suggest we start working on the users module, this module will contain:

1- DB Structure For Users
2- Views (Screen) for login (Mobile + WebApp)
3- Views (Screen) for Users Listing (Mobile + WebApp)
4- Views (Screen) for User Registration (WebApp)
5- Views (Screen) for User Edit Info(Mobile + WebApp)
6- Views (Screen) for User Forget Password (Mobile + WebApp)
7- Model and Controller for all the above

Please let us discuss this issue, before proceeding to the next step.
PS: we'll be using the exact attribute names used by Chiraze's Document in all our project: https://github.com/ChirazeHaidar/vc/blob/master/Etude%20Base%20De%20Donn%C3%A9es.md

**Comment by pascalfares** [comment]
Il serais utile d'expliquer le sens des attribut tel que ici 

https://github.com/ChirazeHaidar/vc/blob/master/Etude%20Base%20De%20Donn%C3%A9es.md
