### ISSUE TITLE
Google Cloud Hosting

### ISSUE THREAD

**Issue by khalilbsaibesisae** [ChirazeHaidar/vc#27]
I have created a Ubuntu Instance on google cloud and Installed Apache Tomcat.
@chreifa Please Deploy a test for the webservices:
IP: 35.194.131.184
UN: khalil_bsaibes
Passphrase: phoenix
SSH_Key: https://drive.google.com/a/isae.edu.lb/file/d/0B27GOXy5t85-Z0xqbW51S2x5T1E/view?usp=drivesdk

**Comment by chreifa** [comment]
Dear Khalil,

kindly close this issue as the environment is now working successfully and ready to be used.

Regards,
