### ISSUE TITLE
Debit & Credit

### ISSUE THREAD

**Issue by ChirazeHaidar** [ChirazeHaidar/vc#32]
@elieohanian, tu as mis dans l'etude de la base de données:
Débit en stock de la branche, cela veut dire entrant (+) comme ajout?
Crédit hors stock de la brancke, cela veut dire sortant (-) comme soustraction?

**Comment by ChirazeHaidar** [comment]
bonsoir @elieohanian, tu as fait des changements dans la base de données. j'ai besoin de savoir quelques informations à propos de ces changements, pour pouvoir créer les tables dans MySQL.

**Comment by elieohanian** [comment]
hi @ChirazeHaidar  oui Debit ajout stock,credit soust stock.

on est besoin dans table transaction(order), et ds table invoice , pour savoir si on veut ajouter ou soustraire dans table  du qty produit par branch
