### ISSUE TITLE
Proposed Grid (Kendo Grid) to be used in our JSP screens

### ISSUE THREAD

**Issue by elyzgheib** [ChirazeHaidar/vc#34]
Grid proposal to use in our screens:
It's Kendo Grid containing many features like:
-sorting
-paging
-advanced search for each field
-batch editing(could be changed easily to popup editing),add, delete
-We read and edit the data by calling web services and by specifying the format of the recieved data.
.....

Push made  the 01/09/2017

**Comment by chreifa** [comment]
kendo is not free. I believe it is better to go with open source library. below is the pricing schema for kendo library:
http://www.telerik.com/purchase/kendo-ui

**Comment by elyzgheib** [comment]
I have the needed js and css files for our grid and we won t need to pay
for anything. Anyway, if there are other propositions that satisfy our
needs then why not!

**Comment by ChirazeHaidar** [comment]
it's already decided them, we can't go with kendo if it's no open source. i will close this issue.
